In [2]:
import pandas as pd

In [8]:
total = (
    pd
    .read_csv('datasets/SAE 2021 Bases statistiques - formats SAS-CSV/CAPACT_PM_PNM/Bases CSV/capact_tot0021.csv', sep=';', encoding='iso-8859-1')
)

total

/tmp/ipykernel_37664/1582505821.py:2: DtypeWarning: Columns (0,2,6,10) have mixed types. Specify dtype option on import or set low_memory=False.
  pd

,fi,an,fi_ej,rs,stj,cat,dep,reg,anc_reg,espic,...,LIT,SEJHC,JOU,PLA,SEJHP,PAS,SEJACC,SEHEM,SERAD,SECHI
0,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,423.0,8810.0,15.0,2854.0,NaN,NaN,NaN,NaN,NaN
1,010000495,2005,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,NaN,...,424.0,4283.0,145112.0,109.0,20943.0,NaN,NaN,NaN,NaN,NaN
2,010000495,2010,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,NaN,...,409.0,6781.0,135981.0,124.0,42635.0,NaN,NaN,NaN,NaN,NaN
3,010000495,2011,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,NaN,...,386.0,6327.0,134649.0,124.0,18518.0,NaN,NaN,NaN,NaN,NaN
4,010000495,2012,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,6.0,...,386.0,6021.0,134222.0,124.0,18875.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74780,980501159,2021,970407250.0,UDM - UAD M'RAMADOUDOU,95.0,141.0,9F,6.0,6.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2258.0,NaN,NaN
74781,980501258,2018,970407250.0,UNITÉ DE DIALYSE MEDICALISEE,95.0,141.0,9F,6.0,6.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3707.0,NaN,NaN
74782,980501258,2019,970407250.0,UNITÉ DE DIALYSE MEDICALISEE,95.0,141.0,9F,6.0,6.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4145.0,NaN,NaN
74783,980501258,2020,970407250.0,UNITÉ DE DIALYSE MEDICALISEE MRAMADOUD,95.0,141.0,9F,6.0,6.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4032.0,NaN,NaN
74784,980501258,2021,970407250.0,UNITÉ DE DIALYSE MEDICALISEE MRAMADOUD,95.0,141.0,9F,6.0,6.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5040.0,NaN,NaN

In [9]:
total.dtypes

fi           object
an            int64
fi_ej        object
rs           object
stj         float64
cat         float64
dep          object
reg         float64
anc_reg     float64
espic       float64
COMINSEE     object
grp         float64
LIT         float64
SEJHC       float64
JOU         float64
PLA         float64
SEJHP       float64
PAS         float64
SEJACC       object
SEHEM       float64
SERAD       float64
SECHI       float64
dtype: object

In [14]:
(
    pd
    .read_csv('datasets/SAE 2021 Bases statistiques - formats SAS-CSV/CAPACT_PM_PNM/Bases CSV/pnm_01_21.csv', sep=';', encoding='iso-8859-1')
    .dtypes
)

/tmp/ipykernel_37664/3829394412.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  pd

fi          object
an           int64
rs          object
grp        float64
stj        float64
cat        float64
reg        float64
anc_reg    float64
dep         object
nat        float64
ADMTO      float64
CADRE      float64
INF        float64
REEDU      float64
AIDES      float64
ASHAU      float64
PSYCH      float64
SAGFE      float64
EDUTO      float64
PHLAB      float64
TECHN      float64
dtype: object

In [62]:
mcoped = (
    pd
    .read_csv(
        'datasets/SAE 2021 Bases statistiques - formats SAS-CSV/Bases statistiques/Bases CSV/MCOPED_2021a.csv',
        sep=';',
        encoding='iso-8859-1',
        dtype='str'
    )
)

mcoped#.sum()

,BOR,AN,FI,RS,FI_EJ,SPED,UPED,LIT_PED,PLA_PED,SEJHP_PED,...,EFFPA_AUX,EFFPA_KINE,EFFPA_PSY,ETP_INFNS,EFFPA_APNM,ETP_PUE,ETP_AUX,ETP_KINE,ETP_PSY,ETP_APNM
0,MCOPED,2021,010000024,CH DE FLEYRIAT,010780054,1,0,22,4,332,...,10,NaN,4,8.95,4,11.64,5.33,NaN,1.63,7.38
1,MCOPED,2021,010000032,CH BUGEY SUD,010780062,1,0,6,1,15,...,2,NaN,NaN,5.24,2,0.09,6.75,NaN,NaN,4.94
2,MCOPED,2021,010005239,CH DU HAUT BUGEY - GEOVREISSET,010008407,1,NaN,10,1,105,...,4,0,1,3.06,1,3.3,7.23,0,0.2,0.88
3,MCOPED,2021,020000162,CH SAINT-QUENTIN,020000063,1,1,20,4,126,...,4,0,2,14.55,11,11.75,19.33,1,3,16.58
4,MCOPED,2021,020000394,CH LAON,020000253,1,1,8,3,5,...,1,0,0,8.59,1,0.32,3.6,0,1,5.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,MCOPED,2021,970400024,CHU SITE FELIX GUYON (SAINT DENIS),970408589,1,1,61,11,1449,...,1,NaN,NaN,23.15,1,6.3,24.08,NaN,1,9.8
310,MCOPED,2021,970400057,CHU SITE SUD (SAINT PIERRE),970408589,1,1,52,6,892,...,2,NaN,2,24.8,6,19,26.6,1,2.5,19
311,MCOPED,2021,970400065,CH OUEST REUNION,970421038,1,1,20,0,0,...,NaN,NaN,1,8.9,5,6.09,4.8,NaN,0.3,15.49
312,MCOPED,2021,970400073,GHER (SAINT-BENOIT),970403606,1,0,8,2,47,...,3,1,0,9.47,1,4.81,12.97,0.31,0,4.47
313,MCOPED,2021,980500011,CHM,980500003,1,1,38,4,358,...,1,NaN,NaN,19.7,1,4.34,13.82,6.45,0.7,20.44

In [38]:
finess_ej = pd.read_csv('datasets/finess_ej.csv', dtype='str')

finess_ej

,nofiness,rs,rslongue,complrs,numvoie,typvoie,voie,compvoie,compldistrib,lieuditbp,...,departement,libdepartement,telephone,statutjuridique,libstatutjuridique,categetab,libcategetab,siren,codeape,datecrea
0,010000156,CLINIQUE CONVERT,CLINIQUE CONVERT,NaN,62,AV,DE JASSERON,NaN,NaN,NaN,...,01,AIN,0428631234,73,Société Anonyme (S.A.),NaN,NaN,772201489,8610Z,2001-01-01
1,010000222,CLINIQUE DU SOUFFLE LE PONTET,CLINIQUE DU SOUFFLE LE PONTET,NaN,311,R,DE LA CHAPELLE,NaN,NaN,NaN,...,01,AIN,0474404949,95,Société par Actions Simplifiée (S.A.S.),NaN,NaN,546120122,8610Z,1961-01-01
2,010000255,ASS.ACCUEIL FORMA INSERT PERSON SOURD,ASSOCIATION POUR LA FORMATION ET L'INSERTION D...,ASS AFIS,5,R,DU LYCEE,NaN,NaN,NaN,...,01,AIN,0474226685,60,Association Loi 1901 non Reconnue d'Utilité Pu...,NaN,NaN,779309194,8710B,2001-01-01
3,010000339,RESIDENCE FONTELUNE,RESIDENCE FONTELUNE,NaN,10,R,DE LA COMMUNE 1871,NaN,NaN,NaN,...,01,AIN,0474461420,21,Etablissement Social et Médico-Social Communal,NaN,NaN,260100011,8710A,2001-01-01
4,010000347,RESIDENCE D'URFE,RESIDENCE D'URFE,NaN,74,R,CONDAMNALE,NaN,NaN,NaN,...,01,AIN,0385304221,21,Etablissement Social et Médico-Social Communal,NaN,NaN,260100029,8710A,2001-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51407,980502231,LIEU DE VIE MAECHA NA BARAKA,NaN,NaN,101,R,DE LA MATERNELLE GNAMBO,NaN,NaN,97650 BANDRABOUA,...,9F,MAYOTTE,NaN,60,Association Loi 1901 non Reconnue d'Utilité Pu...,NaN,NaN,850632860,NaN,2019-01-07
51408,980502280,SAS MDZHADE,NaN,NaN,NaN,IMP,MAHARAJAH,NaN,CENTRE MAHARAJAH - BATIMENT H1,"Z,I KAWENI",...,9F,MAYOTTE,0272741104,95,Société par Actions Simplifiée (S.A.S.),NaN,NaN,899388896,NaN,2021-05-18
51409,980502306,FRANCE ALZHEIMER MAYOTTE,NaN,NaN,1221,AV,DU COLLEGE,NaN,NaN,NaN,...,9F,MAYOTTE,0269602892,60,Association Loi 1901 non Reconnue d'Utilité Pu...,NaN,NaN,822239802,8899B,2016-07-01
51410,980502447,LE CONFORT MEDICAL,NaN,NaN,100,RTE,DES BADAMIERS,C,NaN,LABATTOIR,...,9F,MAYOTTE,NaN,72,Société A Responsabilité Limitée (S.A.R.L.),NaN,NaN,NaN,NaN,2022-09-08
51411,980502462,PHARMACIE AL SHIFAA,PHARMACIE AL SHIFAA,NaN,54,R,Des Manguiers,NaN,NaN,Tsoundzou 2,...,9F,MAYOTTE,NaN,78,Entreprise Unipersonnelle Responsabilité Limit...,NaN,NaN,NaN,NaN,2022-07-25

In [42]:
(
    mcoped
    .merge(
        finess_ej,
        left_on='FI_EJ',
        right_on='nofiness'
    )
    ['libstatutjuridique']
    .value_counts()
    .to_frame()
)

                                                    libstatutjuridique
Etablissement Public Communal d'Hospitalisation                    179
Etablissement Public Intercommunal d'Hospitalis...                  77
Etablissement Public Régional d'Hospitalisation                     23
Association Loi 1901 Reconnue d'Utilité Publique                     7
Fondation                                                            5
Société par Actions Simplifiée (S.A.S.)                              5
Etablissement Public Départemental d'Hospitalis...                   5
Société Anonyme (S.A.)                                               4
Société A Responsabilité Limitée (S.A.R.L.)                          2
Association de Droit Local                                           2
Association Loi 1901 non Reconnue d'Utilité Pub...                   1
Groupement de Coopération Sanitaire Privé                            1
Société Mutualiste                                                   1
Autre Organisme Privé à But non Lucratif                             1
Etablissement Public National d'Hospitalisation                      1

In [40]:
(
    mcoped
    .query('~FI_EJ.isin(@finess_ej.nofiness)')
)

Empty DataFrame
Columns: [BOR, AN, FI, RS, FI_EJ, SPED, UPED, LIT_PED, PLA_PED, SEJHP_PED, SEJHC_PED, JOU_PED, EFFPL_PM, EFFPL_PED, EFFPA_PM, EFFPA_PED, ETP_PM, ETP_PED, GAR_PM, GAR_PED, AST_PM, AST_PED, EFFPL_INFNS, EFFPL_PUE, EFFPL_AUX, EFFPL_KINE, EFFPL_PSY, EFFPL_APNM, EFFPA_INFNS, EFFPA_PUE, EFFPA_AUX, EFFPA_KINE, EFFPA_PSY, ETP_INFNS, EFFPA_APNM, ETP_PUE, ETP_AUX, ETP_KINE, ETP_PSY, ETP_APNM]
Index: []

[0 rows x 40 columns]